# Generated by Django 4.0.3 on 2022-04-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_code', models.IntegerField(max_length=10)),
                ('college_name', models.CharField(max_length=100)),
                ('branch_code', models.IntegerField(max_length=10)),
                ('branch_name', models.CharField(max_length=100)),
                ('status_category', models.CharField(max_length=50)),
                ('open_percentile', models.FloatField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='style',
        ),
    ]
