# Generated by Django 4.0.3 on 2022-04-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_cutoff_delete_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoff',
            name='branch_code',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cutoff',
            name='college_code',
            field=models.IntegerField(max_length=100),
        ),
    ]
