# Generated by Django 4.0.3 on 2022-06-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_alter_cutoff_branch_code_alter_cutoff_college_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoff',
            name='branch_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cutoff',
            name='college_code',
            field=models.IntegerField(),
        ),
    ]
